### PR TITLE
sentiment can now parse emojis

### PR DESCRIPTION
**Pull request by Zandrr**
I've found that emojis are a huge tell as to the real sentiment of a string.  Therefore, I added the ability for this package to parse emojis!

### CODE REVIEW

**Comment by thisandagain** [comment]
Incredible! I've wanted to do this for a while and haven't gotten around to it. Thank you! I'll take a look at this ASAP.

**Comment by Zandrr** [comment]
Woohoo!  I was a bit confused where to add more words to the bucket.  I added some emojis to the AFINN.json file, but they might belong in the .txt file?

Also, this bit in lib/index.js:
```javascript
str = str.filter(function(str) {
    return /\S/.test(str);
});
```
Is to remove extra white spaces.  I noticed that if you had a string like: "I love        chicken"  It would count a bunch of extra spaces.  This change fixes that.

**Comment by Zandrr** [comment]
bump!

**Comment by etiennemarais** [comment]
+1 Please merge this?

**Comment by thisandagain** [comment]
Related to #24

**Comment by thisandagain** [comment]
Closing in favor of #74

**Pull request closed without merging**
